spring:
  cloud:
    stream:
      bindings:
        output:
          destination: provisioning.channel
          group: stock-refill
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 7001
                username: guest
                password: guest